#!/bin/sh
now=`date -u '+%Y-%m-%d %H:%M:%S'`
if head=`git rev-parse --verify HEAD 2>/dev/null`; then
	printf "$now $head"

	# Are there uncommitted changes?
	git update-index --refresh --unmerged > /dev/null
	if git diff-index --name-only HEAD | grep -v "^scripts/package" \
	    | read dummy; then
		printf '%s' -dirty
	fi

	# Is this git on svn?
	if git config --get svn-remote.svn.url >/dev/null; then
		printf -- '-svn%s' "`git-svn find-rev $head`"
	fi
else
	printf "$now - untracked version"  ;
fi